# Generated by Django 4.0.6 on 2024-08-05 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0008_alter_book_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='rating',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
